### ISSUE TITLE
Crucial P2 boot slow

### ISSUE THREAD

**Issue by timjeffrey10** [antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore#1]
Hello,

I am not using this model, but I have a little question I want to ask you.
I have bought Crucual P2 drive and use CCC to backup my macOS Monterey, but the system boot very slow on this drive.

```
tim.jeffrey10@9078414a8c8d ~ % log show --last boot | grep "trims took"
2022-03-11 01:56:08.151823+0800 0x303      Default     0x0                  0      0    kernel: (apfs) spaceman_scan_free_blocks:3153: disk4 scan took 117.390323 s, trims took 116.974521 s
```

I notice that you use this ssd and work successful on Monterey. Do you have this kind of problem or any ideas to fix this?

Thank in advance.

**Comment by antoniomcr96** [comment]
Hi,
how large is your macos partition?
What allocation unit did you set (512byte or 4k)?

Unfortunately this drive has some problems with trim: https://github.com/dortania/bugtracker/issues/192#issuecomment-850963443. It takes more than 10 seconds for my partition (60gb), whereas the process in other disks ends in 4-5 seconds. However, 116s is too much.

It also seems a bit strange because, according to Opencore documentation: 
_On macOS 12+, it is no longer possible to set trim timeout for APFS filesystems. However, trim can be disabled when the timeout value is set to 0._
I thought it meant that the timeout was 9 seconds (standard value of bigsur). Instead, based on what you tell me (116s trim), it seems unlimited.

**Comment by timjeffrey10** [comment]
Thank for your quick reply.

I have tried to shrink my apfs partition size (origion is about 800GB) to 160GB, but the problem is still.
I think the allocation unit is 4k.

```
   Disk Size:                 160.2 GB (160170041344 Bytes) (exactly 312832112 512-Byte-Units)
   Device Block Size:         4096 Bytes
```

- I think the ssd enclosure would also be a problem. Because my purpose is just to backup a bootable OS, I use external disk to boot. I borrowed a supported disk from my friend and tested on the same ssd enclosure and the trim time is about 45s. Therefore, there may be two problems. One is the enclosure ic RTL9210B-CG, and another is Crucial P2. I will consider to buy another enclosure to test it.
- I think trim timeout is cancelled on macOS 12+. It means that we can just to enable trim (`SetApfsTrimTimeout` = -1) or disable trim (`SetApfsTrimTimeout` = 0). The timeout value is no longer used. That's why my trim took so long time.

Also I am curious what your output will be after you type `log show --last boot | grep "trims took"` in the terminal on mac OS 12+.

Thank again.

**Comment by kermit548** [comment]
According to [this thread](https://forums.macrumors.com/threads/trim-on-usb-external-ssd-supported-now.2322611/), it seems like MacOS didn't support TRIM for USB-connected SSDs. Although it can trim now, but may take more time than install inside PC, so I trust that SSD enclosure is one of the reason cause this problem.

[In another thread](https://forums.macrumors.com/threads/new-ssd-formatted-as-apfs-trim-always-slow-boot-and-performance.2237883/post-28496697), someone mentioned that APFS + TRIM may trigger the slow boot bug. It's not 100% hit rate, but can occur. Maybe someone who also uses Crucial P2 SSD inside can provide his trim log.

**Comment by antoniomcr96** [comment]
I didn't understand that you were using an external enclosure. In this case, I agree with @kermit548 . Probably those 116s are the result of the external enclosure + crucial p2 slow trim + apfs file system.
Consider to deactivate trim with the quirk when you boot from the external drive. I don't think replacing the enclosure will solve (or improve) the problem but you can try, let us know.

> * I think trim timeout is cancelled on macOS 12+. It means that we can just to enable trim (`SetApfsTrimTimeout` = -1) or disable trim (`SetApfsTrimTimeout` = 0). The timeout value is no longer used. That's why my trim took so long time.

I agree, Monterey removes the timeout. 

> Also I am curious what your output will be after you type `log show --last boot | grep "trims took"` in the terminal on mac OS 12+.

`2022-03-09 22:03:44.248706+0100 0x418      Default     0x0                  0      0    kernel: (apfs) spaceman_scan_free_blocks:3153: disk1 scan took 20.347263 s, trims took 20.285892 s`

**Comment by timjeffrey10** [comment]
Although 20s is slightly higher than normal, it is still acceptable. It appears that the external enclosure is the main problem.
Since the laptop I use only provides an M.2 slot, I have to use an external SSD.
I will change the external enclosure and try again, if the boot time is still very slow, I will consider disabling TRIM.
Thank you for providing this important information so that I can identify the problem.
