### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by hkbase** [antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore#3]
安装Monterey12.1系统，可以正常使用。
但是在线升级至12.4系统后，无法正常进入桌面，在输入账号密码后，会一直卡在这个界面。
另外在全新安装macos13时，可以进入安装界面，但最后无法顺利完成安装。
感谢您的分享，非常感谢🙏。

**Comment by antoniomcr96** [comment]
I’m using Monterey 12.4 without problems. Your words make me think about a software problem: you should try to reinstall the system.
About macOS 13 I’m not sure if acidanthera team has updated opencore to fully support it. I think we have to wait 
For any further reply, please write in English
