### ISSUE TITLE
Fix Shutdown

### ISSUE THREAD

**Issue by SimbahJohn** [antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore#7]
hi, im install my hackintosh using your efi as reference, im revert it using Intel Wifi, and using lastests Ventura 6.1, and delete your hibernate custom (im not using hibernate), and make custom patch matching my 1.45 bios update. in bigsur all just fine, shutdown work like charm, but in ventura dunno, i cant shutdown this machine, shutdown just go restart, already tried the Shutdown/ Restart Patch Dortania its not help at all, i cant figuring what the problem of this issue, can you help me check about this ? is it related to CPU Friend or UHD Patch, im not sure, but will send the EFI Folder, also my DSDT if needed (im using L390 Yoga Grey (non finger version)) Thank You

**Comment by SimbahJohn** [comment]
done fixed with remap usb, found different layout after bios update

**Comment by antoniomcr96** [comment]
Can you share your usb map here? I’ll try it on my build when I’ll have the possibility

**Comment by SimbahJohn** [comment]
[USBMAP.zip](https://github.com/antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore/files/13669653/USBMAP.zip)
Sure, here its is, sorry for delay, i also change wifi card using Broadcom BCM43xx, from my Fenvi 1200 card, work without any configuration/ any kext, working airdrop, handoff etc,

**Comment by antoniomcr96** [comment]
> i also change wifi card using Broadcom BCM43xx, from my Fenvi 1200 card, work without any configuration/ any kext, working airdrop, handoff etc,

Thanks. What’s exactly the model of the wifi card? Can you send a photo of the card?
