### ISSUE TITLE
error please help

### ISSUE THREAD

**Issue by putra1990** [antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore#8]
![IMG_20240112_043157](https://github.com/antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore/assets/59205929/a7c0edfe-1062-42ba-b235-13dd9a8e88e0)

error after logo apple shutdown
lenovo l390

**Comment by antoniomcr96** [comment]
I think that you forgot to edit your config.plist to add/remove the new values after an update. Maybe this guide could be useful for you: https://dortania.github.io/OpenCore-Post-Install/universal/update.html#_2-mount-your-efi
it shouldn't be anything impossible to solve, and in any case it doesn't depend on the platform (Lenovo) but from a problem in the config.plist file
