### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by kidxiang** [antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore#9]
This is a great repository and hopefully will continue to be updated!

**Comment by antoniomcr96** [comment]
unfortunately, in the last few months, I haven't had a lot of time to dedicate to the development of the project. The purchase of a MacBook Air contributed to this. As soon as I can, I will update the project with the latest opencore and kext releases.

**Comment by kidxiang** [comment]
Thanks so much!
